select * from customer limit 20;

-- what is the revenue generated by male and female customer

select gender, sum(purchase_amount) from customer group by gender;

-- which customers used a discount but still spend more than average purchase amount

select * from customer where pruchase_amount > a
